### ISSUE TITLE
'node deploy.js' doesn't work

### ISSUE THREAD

**Issue by ryokomy** [dev-bootcamp-2019/final-project-N1vas#1]
I tried the following commands reading the README.md.
```
> git clone https://github.com/dev-bootcamp-2019/final-project-N1vas.git
> cd final-project-N1vas.git
> npm install
> cd ethereum
> node compile.js
> node deploy.js
```
However, I had an error while running `node deploy.js` .
`sudo npm run start` shows UI, but I couldn't interact with a contract which didn't exist.

Then, I ran the following commands.
```
> cd ..
> rm -rf package-lock.json node_modules
> npm install
> cd ethereum
> node compile.js
> node deploy.js
```
But it hasn't worked yet. 

Did you try this repository by yourself after writing README.md ? 
I think this does't work on your environment as well. 
Please confirm it. 

Thanks.

**Comment by ryokomy** [comment]
I confirmed that I can interact with pre-deployed rinkeby contract

**Comment by N1vas** [comment]
solved
